export const  FETCH_USER_INFO_REQUEST = 'FETCH_USER_INFO_REQUEST'
export const  FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS'
export const  FETCH_USER_INFO_FAIL = 'FETCH_USER_INFO_FAIL'

export const SELECT_USER_REPO_REQUEST = 'SELECT_USER_REPO_REQUEST'
export const SELECT_USER_REPO_SUCCESS = 'SELECT_USER_REPO_SUCCESS'
export const SELECT_USER_REPO_FAIL = 'SELECT_USER_REPO_FAIL'

export const SELECT_BRANCH_REQUEST = 'SELECT_BRANCH_REQUEST'
export const SELECT_BRANCH_SUCCESS = 'SELECT_BRANCH_SUCCESS'
export const SELECT_BRANCH_FAIL = 'SELECT_BRANCH_FAIL'